### ISSUE TITLE
Forcing extractive output

### ISSUE THREAD

**Issue by iiLaurens** [noamgat/lm-format-enforcer#118]
I work in a field where the consequences of hallucinations are large. The mere possibility of a hallucination makes most LLM projects inviable. It would be of great help if I can provide some sort of guarantee that whatever the model produces is purely extracted from the prompt. That is, there should be a direct hit when searching for that string in the prompt.

Imagine a schema where I ask a question, and I want to collect reasoning, an answer and a quote. The answer would be limited to Yes/No/Unknown, which is easy to enforce. Then the reasoning can be free format, because I want to expose the reasoning of the model (which increases accuracy). Then for the quote, I want the model to only allow sample substrings from the prompt. This last part I am struggling with. Do you think something like this would be possible with LM-format-enforcer?

**Comment by noamgat** [comment]
Interesting. It should be possible to do something like this. You would have to write your own character level parser, that would work something like this:

- in the init, it receives the text in which it quotes
- it keeps a "parsed_string" state of type string, and simply adds to it in "add_character" (self.parsed_string += new_character)
- in get_allowed_characters(), it scans the source string for parsed_string, and collects the following characters of all occurences. These are the allowed characters().
- can_end() always return True.

**Comment by accupham** [comment]
This is a really interesting approach! If performance is an issue with this method, you could always do it as a fallback instead. It's easy to check if the output quote is a substring of the input context. If it's not, then retry with the expensive method.

**Comment by iiLaurens** [comment]
Thanks for the inputs, will give it some thoughts!
