### ISSUE TITLE
sub-100% reliability and long latency on some inputs

### ISSUE THREAD

**Issue by stephenleo** [noamgat/lm-format-enforcer#119]
Hello. I'm the author of [LLM Structured Output Benchmarks](https://github.com/stephenleo/llm-structured-output-benchmarks), which compares multiple LLM structured output parsers on standard inputs. 

I posted my findings on [Linkedin](https://www.linkedin.com/posts/marie-stephen-leo_generativeai-llm-nlp-activity-7215519900893683712-zVaa). Following up here with a minimal example to aid in troubleshooting

Error while parsing JSON leading to low reliability and high latency minimal working example:
```python
# Imports
from enum import Enum
from pydantic import BaseModel
from lmformatenforcer import JsonSchemaParser
from lmformatenforcer.integrations.transformers import build_transformers_prefix_allowed_tokens_fn
from transformers import pipeline
import json

# Response schema
# very long latencies and un-parseable
problem_texts = [
    "give details of rock sand",
    "please make the lights natural",
    "describe a sloth",
    "what is the temperature in indianapolis indiana. what features do you have planned to release in the future. boiling. change the lights in the living room to green and red",
    "play pride and prejudice",
]

# ok_texts[2] has marginally longer latency but is still parseable
ok_texts = [
    "can you do nine plus two",
    "turn my lights down to a lower level of brightness",
    "any breaking news from the huffington post. what is my schedule for the day. find songs from my big band playlist. play country radio",
]

class_list = ["lists_createoradd","calendar_query","email_sendemail","news_query","play_music","play_radio","qa_maths","email_query","weather_query","calendar_set","iot_hue_lightdim","takeaway_query","social_post","email_querycontact","qa_factoid","calendar_remove","cooking_recipe","lists_query","general_quirky","alarm_query","takeaway_order","iot_hue_lightup","lists_remove","qa_currency","play_game","play_audiobook","qa_definition","music_query","datetime_query","transport_query","iot_hue_lightoff","iot_hue_lightchange","iot_hue_lighton","alarm_set","music_likeness","recommendation_movies","transport_ticket","recommendation_locations","audio_volume_mute","iot_wemo_on","play_podcasts","datetime_convert","audio_volume_other","recommendation_events","alarm_remove","iot_coffee","music_dislikeness","general_joke","social_query"]

def multilabel_classification_model(multilabel_classes):
    class MultiLabelClassification(BaseModel):
        classes: list[
            Enum("MultilabelClasses", {name: name for name in multilabel_classes})
        ]

    return MultiLabelClassification

response_model = multilabel_classification_model(class_list)

# LMFE Setup
parser = JsonSchemaParser(response_model.schema())
hf_pipeline = pipeline(
    "text-generation",
    model="unsloth/llama-3-8b-Instruct-bnb-4bit",
    device_map="cuda",
    max_length=4096,
    truncation=True
)
prefix_function = build_transformers_prefix_allowed_tokens_fn(
    hf_pipeline.tokenizer, 
    parser
)

# Run on one text
prompt_template = "Classify the following text: {text}.\nRespond in the following json schema: {json_schema}:\n"
prompt = prompt_template.format(
        text=problem_texts[0],
        json_schema=response_model.schema()
    )
response = hf_pipeline(prompt, prefix_allowed_tokens_fn=prefix_function)
response = response[0]["generated_text"][len(prompt) :].strip()
print(json.loads(response))
```

Other Info:
- Windows WSL2
- `lm-format-enforcer==0.10.3`
- NVIDIA GTX 4080 SUPER
- CUDA Version: 12.4

Pls let me know if there's any other info that can be relevant for this investigation.

**Comment by noamgat** [comment]
Hi! I've ran your sample and I don't see an issue with LM Format Enforcer so far.
The case where the output is not json parseable only occurs when the response is stopped due to the token limit (And not due to the language model outputting an EOS token). This makes sense (because the output was truncated mid way).
If I add a list length limit to the class definition:

```
from pydantic import BaseModel, Field

def multilabel_classification_model(multilabel_classes):
    class MultiLabelClassification(BaseModel):
        classes: list[
            Enum("MultilabelClasses", {name: name for name in multilabel_classes})
        ] = Field(None, min_length=1, max_length=100)

    return MultiLabelClassification
```

I get 100% legal outputs. While the class tries to define a multilabel enum schema, in reality it can have the same class appear an unlimited amount of times (this is what the json schema dictates). After limiting the length of the list, I get consistently legal outputs for all of your problematic examples.
Is this not the case for you? Do you expect LM Format Enforcer to generate legal schema objects even in truncated output cases? Did you get illegal completions without reaching the token limit? Will be happy to hear your experience and find the root issue.

**Comment by noamgat** [comment]
Can you rerun the benchmark with the latest released version (v0.10.4)?
It adds a heuristic that limits the array length to 20 unless specified otherwise by the schema or config. Similar to how whitespaces are limited by default. I get 100% reliability in the benchmark now.

**Comment by stephenleo** [comment]
Hey thanks for the feedback. I'll update, rerun the benchmark and report back!

**Comment by stephenleo** [comment]
0.10.4 gives perfect realiability and reduces the latencies as well. I've updated my benchmarks!

![image](https://github.com/user-attachments/assets/b0f98537-6cbc-4ce4-9462-2b3ded47ac71)

**Comment by noamgat** [comment]
Thanks for updating! The benchmark looks awesome
