### ISSUE TITLE
Add support for Ollama

### ISSUE THREAD

**Issue by sutyum** [noamgat/lm-format-enforcer#12]
Ollama is an increasingly popular way of running local llm models. Its a CLI which behaves like a package manager for LLMs. It downloads and uses GGUF files.

**Comment by noamgat** [comment]
From what I see in its source code, it is written in Go, and the python interface talks to it via HTTP. This means that there is no method to run python code inside the sampling mechanism, which will make LMFormatEnforcer integration very difficult.

Am I mistaked about what I understood about Ollama?

**Comment by sutyum** [comment]
You're right

**Comment by cognitivetech** [comment]
now it shares common api

https://github.com/ollama/ollama/blob/main/docs/api.md
