### ISSUE TITLE
Breaking out of SequenceParser

### ISSUE THREAD

**Issue by iiLaurens** [noamgat/lm-format-enforcer#121]
Currently the sequence parser is sticky and will always return either another SequenceParser or when faced with ambiguity, an UnionParser. I think some CPU cycles can be saved if SequenceParser pushes out completed parsers and at the very last parser just return the parser on `add_character`.

Here is a trivial example:

```python
# Sequence parser that only accepts the string 'abc'
seq = [StringParser('a'), StringParser('b'), StringParser('c')]
parser = SequenceParser(seq)

parser = parser.add_character('a')
print(type(parser))  # Returns another SequenceParser as expected
print(len(parser.parsers))  # Contains 3 parsers even though we already consumed the first

parser = parser.add_character('b')
print(type(parser))  # Returns another SequenceParser, but we know only StringParser('c') is left. Why not simply return the last parser?
print(len(parser.parsers))  # Contains 2 parsers even though we already consumed the first two
```

I understand that due to more complicated cases with ambiguity, it will not always be possible to simplify the SequenceParser. But I would expect simplification for trivial cases, such that no cpu cycles need to be wasted on evaluating SequenceParsers.

**Comment by noamgat** [comment]
Can you check if you get behavior that more closely matches your expectations after this commit: https://github.com/noamgat/lm-format-enforcer/commit/20e0b6d0e5ddb03be8b2061a4c8866b52b4614c5

**Comment by iiLaurens** [comment]
This works! It is able to break out of the SequenceParser now. It's not breaking out at the earliest opportunity as could be (after seeing 'b' it could already know only the last parser is left). But I think detecting whether to break out earlier requires more code and cycles, and might break some of the elegance of the code. This is definitely good enough!
