### ISSUE TITLE
Unknown LMFormatEnforcer Problem & AttributeError with "additionalProperties": true

### ISSUE THREAD

**Issue by gittb** [noamgat/lm-format-enforcer#129]
Good afternoon,

When using the following json schema, I get an `Unknown LMFormatEnforcer Problem.`

Here is the prefix:

```Prefix: '[
    {
     "id": "tool_id_1342",
     "function": {
     "arguments": {
'
```
Here is the schema:

```
openai_tool_call_schema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "function": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "arguments": {
            "type": "object",
            "additionalProperties": {
              "oneOf": [
                { "type": "string" },
                { "type": "number" },
                { "type": "object" },
                { "type": "boolean" },
                { "type": "array" },
                { "type": "null" }
              ]
            }
          }
        },
        "required": ["name", "arguments"]
      },
      "type": {
        "type": "string",
        "enum": ["function"]
      }
    },
    "required": ["id", "function", "type"]
  }
}
```

I only moved to this because I was running into this error `validate_exclusive_maximum_and_exclusive_minimum
    exclusive_maximum: Union[float, bool, None] = values.get('exclusiveMaximum')
AttributeError: 'bool' object has no attribute 'get'` when I tried to use the same schema as above, but with arguments as below. 

```
          "arguments": {
            "type": "object",
            "additionalProperties": True
          }
```
This didn't make sense as to why we would be trying to get this value from a bool, so I moved to the above more verbose schema to hopefully avoid it and ended up here.

(True is Cap T because I'm defining this as a python dict prior to it being used)

I'm not sure what the best way to capture the `CharacterLevelParser` parameters is, as I'm using lm-format-enforcer within [TabbyAPI](https://github.com/theroyallab/tabbyAPI/pull/154) on a PR. If you can advise where I could either log this, or print it out I can provide it here.

**Comment by victbr** [comment]
same issue that parser cannot handle `"additionalProperties": True`. I think it will not affect the constraint output(we can just ignore it?), but it is a legal input and will crash the program.

**Comment by victbr** [comment]
But I have some problem about your prefix and schema, the prefix is begin with '{', but the schema type is array, which should begin with `[` I guess?

**Comment by DhruvaBansal00** [comment]
I am facing this same issue! This is a relatively serious issue since schemas for OpenAI's structured outputs require setting additionalProperties to False: https://platform.openai.com/docs/guides/structured-outputs/additionalproperties-false-must-always-be-set-in-objects. The Parser crashes with additionalProperties set to False as well at the moment. This means that we can't use the same schemas for OpenAI and vLLM hosted models. cc: @noamgat

**Comment by noamgat** [comment]
@DhruvaBansal00 can you supply a schema + legal completion that doesn't work for you?

**Comment by DhruvaBansal00** [comment]
@noamgat here is a schema that fails:

`{'title': 'AnswerFormat', 'description': 'Answer to the provided prompt.', 'type': 'object', 'properties': {'snippets': {'title': 'snippets', 'type': 'string'}, 'overall_sentiment': {'title': 'overall_sentiment', 'type': 'string'}}, 'required': ['snippets', 'overall_sentiment'], 'additionalProperties': False, 'definitions': {}}
`
Legal completion:

`{"snippets": "What a beautiful day", "overall_sentiment": "Positive"}`

**Comment by noamgat** [comment]
I just pushed a fix to master. Can you verify it works as expected before I release it?

**Comment by DhruvaBansal00** [comment]
Thanks for the quick fix. I'll get back to you by EOD - need some time to rebuild the vllm image with the latest commit here.

**Comment by DhruvaBansal00** [comment]
@noamgat I have verified that the fix works!

**Comment by gittb** [comment]
I can check for my original query in a moment. Thanks for reviving this @DhruvaBansal00

**Comment by gcalmettes** [comment]
@noamgat I am also confirming that master fixes the similar errors I had with a boolean `additionalProperties` in json schema
