### ISSUE TITLE
Non-ASCII characters break the output

### ISSUE THREAD

**Issue by remixer-dec** [noamgat/lm-format-enforcer#13]
Hi, I tried the llama.cpp example and noticed that this library cannot handle non-ascii characters correctly by default and it stops right after running into such character. 
<img width="374" alt="image" src="https://github.com/noamgat/lm-format-enforcer/assets/6587642/9b52b886-454c-42b4-be49-5d4ae8b7f653">
<img width="354" alt="image" src="https://github.com/noamgat/lm-format-enforcer/assets/6587642/9e72f1d4-32cd-40e1-97ea-e02e7e9f6f98">
Is it possible to allow these characters?

**Comment by noamgat** [comment]
Hi! This is indeed a current limitation of the library, I hope to address it soon.

**Comment by noamgat** [comment]
```python
class AnswerFormat(BaseModel):
    emoji_strings: List[str]

question = 'What are the 10 most common emojis? You MUST answer using the following json schema: '
```

now leads to

```
  {
"emoji_strings": [
"😊",
"👍",
"🤣",
"🚀",
"🎉",
"❤️",
"🤔",
"🙏",
"💭",
"😢",
"😠"] }
```

**Comment by remixer-dec** [comment]
Amazing!

**Comment by jorge-tromero** [comment]
I'm facing this issue with the transformers integration, and vllm. The generate loop always exits after non-Ascii characters, because can_end() starts returning True.
