### ISSUE TITLE
[BUG ]haystackv2 integration : Importing LMFormatEnforcerLocalGenerator raise Error

### ISSUE THREAD

**Issue by Kaelancode** [noamgat/lm-format-enforcer#135]
```from lmformatenforcer.integrations.haystackv2 import LMFormatEnforcerLocalGenerator```

raise error ModuleNotFoundError: No module named 'haystack.preview'

haystack-ai == 2.4 
 lm-format-enforcer == 0.10.6

does not work on older versions too of 
haystack-ai  and  lm-format-enforcer

**Comment by noamgat** [comment]
Thanks for raising this! This looks like a version compatibility issue. I hope to get to it in a few days, but if you can fix the imports to be up to date, I would be happy for a PR :)

**Comment by noamgat** [comment]
Fixed in version 0.10.7
