### ISSUE TITLE
How to specify schema format in vllm api servers ?

### ISSUE THREAD

**Issue by thangld201** [noamgat/lm-format-enforcer#147]
Hi @noamgat, thank you for your works!

I am trying to use guided-decoding-backend with lm-format-encoder in vllm openai server.
Currently I am trying this:
```
vllm serve /path/to/model/Llama-3.1-8B-Instruct --dtype bfloat16 --enforce-eager --host 127.0.0.1 --port 8000 --gpu-memory-utilization 0.95 --guided-decoding-backend lm-format-enforcer
```

And when forwarding the request, I just use openai client e.g.
```
client.chat.completions.create(
    messages=[
            {
            "role": "user",
            "content":prompt
            },
        ],
        model=model,
        max_tokens=max_tokens,
        temperature=temperature,
        seed=seed
    )
```

My question is how to specify that I want strictly a json object as return (not pydantic, regex ..), and that json object follows specific schemas e.g. {'a':..., 'b':...} ? 

I did not find this in the documentations, so I'm likely missing something... 

EDIT: I realized that one can add `extra_body=dict(guided_json=json_template)` in the `create()` function with `json_template` as some arbitrary json schemas: e.g. 
```
{
    "type":"object",
    "properties": {
        "output": {
            "type":"object"
        }
    }
}
```

**Comment by paguilomanas** [comment]
Does it work for you as expected? I am unable to obtain a proper json output

**Comment by thangld201** [comment]
> Does it work for you as expected? I am unable to obtain a proper json output

Yes, it did. I used latest vllm version btw.
