### ISSUE TITLE
JSON Escaping isn't supported

### ISSUE THREAD

**Issue by remixer-dec** [noamgat/lm-format-enforcer#15]
When I was writing a report for my previous issue, I ran some tests and accidentally faced one more bug!

If the model produces a backslash (possibly as the last character in the string), it stops and breaks the final output
<img width="800" alt="image" src="https://github.com/noamgat/lm-format-enforcer/assets/6587642/afc84027-bf34-437d-a28b-7d0bc798a94e">

**Comment by remixer-dec** [comment]
<img width="810" alt="image" src="https://github.com/noamgat/lm-format-enforcer/assets/6587642/9827b67b-a100-46a8-ada9-0cab0149d956">

Another example, this time it's not only `\` but `\"`

**Comment by noamgat** [comment]
Yes, this is a known issue. JSON escaping is not supported at all yet.

**Comment by noamgat** [comment]
Should be solved in v0.5.2. Can you confirm before I close the issue?

**Comment by remixer-dec** [comment]
Thanks for a quick fix. Seems to be working correctly now, escaped characters appear in a string without breaking it.
I ran into another bug though, probably unrelated to this, will report it in another issue. Sorry!
