### ISSUE TITLE
Newlines inside strings break the parser and incomplete JSON is generated

### ISSUE THREAD

**Issue by remixer-dec** [noamgat/lm-format-enforcer#18]
When the parser runs into an un-escaped line break, it stops and produces a broken JSON.

```json

 {
  "task": "Choose the best action to solve this complex problem.",
  "problem": "When was the specified game released? Game name: <name>",
  "solution_plan_explained_step_by_step": "Step 1: Browse the web to find information about <name> game release date.

```

In the schema all items have `str` type, naming the key `step_by_step` makes it more likely to produce line-breaks.
I see two ways out of this situation: 1) ban line-breaks in strings, 2) escape line-breaks in strings. 
Not sure which one is better.

**Comment by noamgat** [comment]
Thanks for the report! Line breaks should be forbidden inside JSON strings,
as that is how the JSON spec works. Confirmed bug.
