### ISSUE TITLE
What is the difference wrt LMQL?

### ISSUE THREAD

**Issue by ogencoglu** [noamgat/lm-format-enforcer#3]
What is the difference of your library vs LMQL?

**Comment by noamgat** [comment]
LMQL mixes two approaches to controlling output - prompt engineering and constraints.

In its [constraint page](https://lmql.ai/docs/language/constraints.html) you can see what can be done with constraints (that prevent the LLM from generating tokens that violate the format). Note that JSON Schema is not there.

JSON Schema is done via [prompt engineering and verification](https://github.com/eth-sri/lmql/blob/51c92b0070fab008b117d3b60c6c9c97be78bc0d/src/lmql/ui/playground/src/queries.js#L71), similar to [Typechat](https://github.com/microsoft/Typechat).

This library only uses the constraint approach, and is able to correctly filter the tokens allowed at the next timestep that can eventually turn into correct output, ensuring format-compliant outputs in the first iteration.

**Comment by ogencoglu** [comment]
Thanks for the swift reply!
