### ISSUE TITLE
Outputting invalid json & skipping schema attributes

### ISSUE THREAD

**Issue by jpeig** [noamgat/lm-format-enforcer#31]
Love your project and I've been using it extensively now with vllm.

However, what I noticed is that by default, the llm-format-enforcing is not enforcing the schema (as opposed to Jsonformer - which I used before) and has a tendency of wrapping up / ending the output prematurely by skipping attributes, especially those at the end of the schema. 

A sample of some output:
`{\n        "event_body": "As you continue your journey in the Dutch Golden Age, you find yourself at a crossroads. The city\'s bustling trade and art scene have brought new opportunities for growth, but also challenges that require strategic decision-making. You must choose between three paths: deepening your knowledge of the world through \'Insight\', strengthening your leadership abilities with \'Force\', or enhancing your diplomatic skills with \'Diplomacy\'. Each path will shape not only how you navigate this era but also how others perceive and interact with you. As the clock ticks, it\'s time to make a choice that will define who you become during this remarkable period in history",\n        "location": "The Golden House",\n        "trigger_time_of_day": "evening",\n        "option-1": {\n           "player_option": "\'Insight\' - Dive deeper into understanding the world around us through intellectual exploration and wisdom",\n           "internal_dialogue": "I need to expand my knowledge to better navigate this era." \n        }, \n        "option-2": { \n          "player_option":"\'Force\' - Strengthen our physical prowess while maintaining honorable leadership qualities", \n          "internal_dialogue":"I should focus on building my strength and character for effective leadership."   },  \n         "option-3": {  \t\t\t\t\t\t  \t"player_option":"\'Diplomacy\' - Develop strong interpersonal relationships by fostering harmony among people from various backgrounds", \n          "internal_dialogue":"It is crucial to maintain good relationships for success in this era."},    \n       }
`

For every "option-x" it skipped "challenges", "success_effects" and "failure_effects". At the end, the output should have finalized with an object called 'trigger_conditionals', but instead it closed the object in spite of the generated comma. All of these attributes have been defined in my schema. 

My fix up to now is adding the "required" attribute to the schema, but this is quite tedious and may not be waterproof.

Furthermore, as you can see it ended the response with a comma - which is not valid JSON. The fact that it can output a response that is not valid JSON is concerning.

Any recommended approaches to tackling this problem?

Note: I am using main branch and employing the logitsprocessor of the vllm integration.

**Comment by noamgat** [comment]
Hi!
Happy to hear that the library is helping you.
1) By default, I think objects are not mandatory in a json schema. The project aims to be as 100% json-schema compliant as possible. If you find, that in the json schema definition, an object without a `required` array means that all fields are required, please link me to it and I will change the parser accordingly. Otherwise, it is possible to add a field to CharacterLevelParserConfig that controls this behavior (maybe `json_objects_require_all_fields_by_default: bool`) and change the behavior of JsonSchemaParser to use this flag.

2) The trailing comma looks like a bug! It should be possible to submit a unit test that reproduces this. Can you send the schema that you used + the string that you received, and I will see if the parsing tree indeed accepts the trailing comma?

**Comment by noamgat** [comment]
- Order of output does not have to correspond to order in schema, this is a feature, not a bug. Field order is meaningless, and not forcing it gives the LLM more freedom to express itself, reducing hallucinations.
- Can you please upload a "concrete" json schema + example output, without templating logic, so I can easily create a unit test from it?

**Comment by jpeig** [comment]
- While field order is considered meaningless for structured schema output, field order is not meaningless to the LLM. E.g. some field can be better filled in after another has been filled in first.
- See [this issue](https://github.com/noamgat/lm-format-enforcer/issues/34) for a concrete schema + example output

**Comment by noamgat** [comment]
v0.10.1 added support for strict json schema field ordering.
Several json schema parsing bugs have been fixed since this issue was raised. Can you check if they still happen? Please reopen if they do.
