### ISSUE TITLE
Halucinations? how to set null

### ISSUE THREAD

**Issue by codenamics** [noamgat/lm-format-enforcer#35]
Hello,

Packsge works pretty good but cna you tell me how to enforce null on None example.

`class AnswerFormat(BaseModel):
    age: str
    height: str
    temperature: int
    systolic_blood_pressure: int
    diastolic_blood_pressure: int
    # respiratory: int
    pulse: str
    is_preg: bool
    heart_rate: int`

text = """
23-year-old pregnant woman at 22 weeks gestation presents with burning upon urination. 
She states it started 1 day ago and has been worsening despite drinking more water 
and taking cranberry extract. She otherwise feels well and is followed by a doctor for her pregnancy. 
Her temperature is 97.7°F (36.5°C), pulse is 80/min, 
respirations are 19/min, and oxygen saturation is 98% on room air. Physical exam is 
notable for an absence of costovertebral angle tenderness and a gravid uterus.
"""

`{
"age": "23",
"height": "165",
"temperature": 977,
"systolic_blood_pressure": 120,
"diastolic_blood_pressure": 80,
"pulse": "80",
"is_preg": true,
"heart_rate": 80
}`

as we can see blood pressure is not present in prompt but LLM fill it i think by default value

I tried `Union[float, None] = None` but not respected

any idea?

**Comment by codenamics** [comment]
I will close it but please take a look at it as i think i most cases null or None should be done becasue halucinatons are bad:) maybe apply pydantic after output?

**Comment by ivsanro1** [comment]
> I reckon that the only true way to solve this, is to fine-tune the LLM with cases where the field is optional, the data is not present and it will eventually "learn" that optional fields are not required.

@noamgat the problem of this is that if you ask the LLM to extract A, B, C, it will tend to output the whole json structure, i.e. generating the keys, and then after the key, it has to decide whether it has a value or `null`.

In other words, forcing the LLM to "lookahead" and not put the key directly if the value cannot be found, which is the workaround using optional fields, is a harder task for them in general. 

For this, it would still be great if lm-format-enforcer allows `null` values even if fields are optional, or nullable fields with union types, e.g.:

```
{
  "year": {
    "type": ["number", "null"]
  }
}
```

**Comment by noamgat** [comment]
You can achieve this by typing a pydantic field as Optional[ActualType]
instead of ActualType
