### ISSUE TITLE
Is this tool related to LLM? Does it support ChatGLM?

### ISSUE THREAD

**Issue by pia-ai** [noamgat/lm-format-enforcer#40]
Is this tool related to LLM (Language Learning Models)? Does it support ChatGLM?

https://github.com/THUDM/ChatGLM2-6B

**Comment by noamgat** [comment]
Yes, it enforces JSON / regex output for large language models. The ChatGLM page you linked to shows an example with transformers library, which this library supports. See the [main sample notebook](https://colab.research.google.com/github/noamgat/lm-format-enforcer/blob/main/samples/colab_llama2_enforcer.ipynb) for an example.
