### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by unoriginalscreenname** [noamgat/lm-format-enforcer#48]
The example you have to get started and demonstrate the package doesn't work.  There are issues with the pydantic json_schema call needing to be replaced with model_json_schema and then several other warnings that get generated:

UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.

UserWarning: Input length of input_ids is 152, but `max_length` is set to 20. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`. 

There is no result returned.  This seems like a promising library, maybe take a look at the starting code for us first timers.  I was unable to fix it on my own.

**Comment by noamgat** [comment]
Hi!
Which example did you use? The notebook or the snippet in the README?
I released a new version today, the sample might need to be updated.

**Comment by noamgat** [comment]
I just created a notebook with the snippet from the example:

https://colab.research.google.com/drive/12BlBxr_DaPnV3tfuzp7U7jIXzD2OQ6w-

And it works:

```
{
"first_name": "Michael",
"last_name": "Jordan",
"year_of_birth": 1963,
"num_seasons_in_nba": 15
}


```

Can you specify exactly what you did?

**Comment by noamgat** [comment]
Is this a model I can use? I will be happy to assist if I can reproduce the problem.

**Comment by noamgat** [comment]
Integrating with server APIs is harder, software design wise, as we don't want to alter the server itself.
The easiest way would be to fork the server code, add an optional parameter to the API call, and instantiate the json schema parser accordingly, but then you would be maintaining a fork.

The only way to do this without modifying the server itself, is to add a plugin interface to the inference servers.
I've submitted a [PR draft to huggingface-text-inference](https://github.com/huggingface/text-generation-inference/pull/1274), but no engine has integrated such a solution yet.
