### ISSUE TITLE
Tokenizer must not contain empty tokens Error

### ISSUE THREAD

**Issue by unoriginalscreenname** [noamgat/lm-format-enforcer#54]
Hi, I'm working with this library and llamacpp.  I've started to get an error on certain models (not all) when running the build_token_enforcer_tokenizer_data funtion.  

lmformatenforcer\tokenizerprefixtree.py", line 57, in freeze
    assert not any(t == '' for t in all_tokens), "Tokenizer must not contain empty tokens"
AssertionError: Tokenizer must not contain empty tokens

This is happening on several models, but you should be able to reproduce it on NeuralHermes-2.5-Mistral-7B-GGUF.

Do you have any idea why this would be happening?

**Comment by noamgat** [comment]
I think I fixed the problem (it came from an assumption from a recent PR).
Can you try installing the library using:

```pip install git+https://github.com/noamgat/lm-format-enforcer.git@bugfix/tokenizer_with_empty_tokens```

And report if the crash is gone?

**Comment by pinoloricato** [comment]
This change fixes the error above for me, however it sometimes results in generating invalid JSONs: 

Invalid JSON: EOF while parsing a value at line 1 column 0 [type=json_invalid, input_value='',                │
│ input_type=str]

**Comment by kaciuk** [comment]
> I think I fixed the problem (it came from an assumption from a recent PR). Can you try installing the library using:
> 
> `pip install git+https://github.com/noamgat/lm-format-enforcer.git@bugfix/tokenizer_with_empty_tokens`
> 
> And report if the crash is gone?

I had the same issue and this fix solved it.

**Comment by noamgat** [comment]
Released in 0.8.2
