### ISSUE TITLE
What will happen when generating tokens that do not meet the requirements

### ISSUE THREAD

**Issue by Vincentyua** [noamgat/lm-format-enforcer#56]
Amazing job, I want to know how to proceed if the generated token does not meet the requirements when it is forcibly generated, whether to roll back and regenerate the token or filter and regenerate the token. I don't seem to see this in the repository, and I hope to get an answer! @noamgat

**Comment by noamgat** [comment]
This should never happen with LMFE, as the logit of any token that would produce an illegal result should get `-inf` score. If this happens, it is a bug in LMFE. Ideally, submit a unit test with the schema you used and the illegal output you received. If you can't do that, attach the case here and I'll build a unit test from it.

**Comment by Vincentyua** [comment]
Thank you very much for your reply! I'm just curious about how to handle this phenomenon, and I also have a question, can LMFE only load quantized models? Can some of the latest non quantitative models, such as Qwen-7B-chat and Baichuan-7B-chat, be directly replaced and used? I have encountered some problems during use (various), and the provided samples have not been run through yet. I really hope to receive your help

**Comment by noamgat** [comment]
It should work with any model. If there is a model that is not supported, can you please attach an example so I can debug?
