### ISSUE TITLE
Will it support generating multiple JSON in the future?

### ISSUE THREAD

**Issue by Vincentyua** [noamgat/lm-format-enforcer#64]
In practical application, it may be necessary to generate multiple JSONs.
For example, ”what is the weather like in Chicago and Los Angeles?“，Given a weather API, the model generates two JSON API calls for weather queries based on this API

 Do you have a plan to support this feature? When will it be supported approximately?
Very much looking forward to it！

**Comment by noamgat** [comment]
Hi! It should be possible by defining a single smart schema - either using List or an object.
