### ISSUE TITLE
Issue with llamacpp version larger than 0.2.37

### ISSUE THREAD

**Issue by isamu-isozaki** [noamgat/lm-format-enforcer#72]
@noamgat I haven't fully looked into this but on version 0.2.38 of llamacpp with this library and outlines as well, the generation fails.
The change to llamacpp 0.2.37 does fix both libraries' generation problems while both does struggle with 0.2.38. The outlines devs seem to have a fix [here](https://github.com/abetlen/llama-cpp-python/pull/1179)

**Comment by michael-newsrx** [comment]
According to the llama-cpp-python changelog, they fixed an off-by-one error in version 0.2.42.

https://github.com/abetlen/llama-cpp-python/blob/main/CHANGELOG.md

**Comment by isamu-isozaki** [comment]
Oh awesome I'll test out

**Comment by noamgat** [comment]
Verified that new version is working. Closing.
