### ISSUE TITLE
build_token_enforcer_tokenizer_data takes too long on some tokenizer 

### ISSUE THREAD

**Issue by gsolard** [noamgat/lm-format-enforcer#73]
When using the function build_token_enforcer_tokenizer_data on the bloom tokenizer (https://huggingface.co/bigscience/bloom), it takes a really long time to finish.

The problem comes from this loop : https://github.com/noamgat/lm-format-enforcer/blob/7cfb693495e9ba3305e230cc62e05b383b6c717a/lmformatenforcer/tokenizerprefixtree.py#L72

Indeed one decoded token in the bloom tokenizer have length 600 and several have a length superior to 100 (compared to 16 maximum for llama for example). So the double loop is really long to complete

**Comment by noamgat** [comment]
A PR that will soon be merged allows limiting the max string length in this
section, will improve performance
