### ISSUE TITLE
Batching with vLLM

### ISSUE THREAD

**Issue by keyboardAnt** [noamgat/lm-format-enforcer#9]
Hi @noamgat,

First off, thanks for this cool repo!

I was going through the [sample notebook for the vLLM integration](https://github.com/noamgat/lm-format-enforcer/blob/main/samples/colab_vllm_integration.ipynb) and noticed that it doesn't implement batching, unlike the [sample for the HuggingFace's `transformers` integration](https://github.com/noamgat/lm-format-enforcer/blob/main/samples/colab_llama2_enforcer.ipynb). 

Is there a specific reason for this difference? Just curious to know!

**Comment by noamgat** [comment]
Hi! The vLLM integration supports batching, it just wasn't covered in the demo to keep it simpler. PRs welcome :)

The only thing I would pay attention to, is that you want to apply the monkeypatch once, outside of the batching loop.

**Comment by noamgat** [comment]
Also, if this PR is accepted by vLLM, it will make the integration much more elegant:

https://github.com/vllm-project/vllm/pull/1469

Please thumbsup on the PR so the vLLM team know :)

**Comment by keyboardAnt** [comment]
Hi @noamgat,

Thanks for replying!

> The vLLM integration supports batching, it just wasn't covered in the demo to keep it simpler.

[A preliminary experiment](https://drive.google.com/file/d/1gyyvEpZe042uOHpjGhxbZodm1vKYfCr9/view?usp=sharing) suggests that the latency scales linearly with respect to the _requested_ batch size (I didn't check the _actual_ batch size used by vLLM's dynamic batching). What am I missing?


| ![image](https://github.com/noamgat/lm-format-enforcer/assets/15572698/719fb7a7-e532-40d8-939f-96895a8fc2f4#center) |
|:--:| 
| *Latency in seconds (y-axis) over the number of requested prompts (x-axis)* |

**Comment by noamgat** [comment]
Added a batching example to the vllm sample notebook here:
https://github.com/noamgat/lm-format-enforcer/blob/main/samples/colab_vllm_integration.ipynb

I am receiving better time-per-prompt when making the jump from 1 to 20. Above the batch size, you expect to see linear results.

**Comment by keyboardAnt** [comment]
@noamgat, thank you for adding a batching example to the vLLM sample notebook. Can you specify which version of vLLM you used for this? I've noticed that the current commit on the main branch of vLLM already [implements](https://github.com/vllm-project/vllm/blob/5687d584fe4825d59a6fd9ecc5840e1df04e380f/vllm/entrypoints/llm.py#L157) a similar procedure.

Regarding your observation on the improvement in time-per-prompt from batch sizes of 1 to 20: Could you share specific numbers to illustrate this? Additionally, when you mentioned expecting to see linear results for batch sizes above 20, could you share data or insights on how the performance scales for those larger batch sizes?

**Comment by noamgat** [comment]
My timings, as seen in the example notebook after the update:

Time taken for 1 player: 1.8789570331573486
Time taken for 19 players: 6.5615339279174805. Time per player: 0.3453438909430253

I ran it several times and got consistent results.

I am not a vLLM expert so I cannot dive much deeper into vLLM, but this does show that something is working.

**Comment by keyboardAnt** [comment]
Thanks @noamgat! Before I close this issue, I wanted to share the results below:

I repeated the previous experiment, but [this time](https://colab.research.google.com/gist/keyboardAnt/49f8798b8709e718ba6c702e5eff4790/copy-of-colab_vllm_integration.ipynb) I measured only the latency of the inference (i.e., not including the latency of Pydantic—as in the previous experiment). On Google Colab with a single T4 GPU, it seems like the latency of generating batches of sizes 1, 10, 20, 32, 64, and 100 remains linear with respect to the batch size, and we can fit the following linear line:

![image](https://github.com/noamgat/lm-format-enforcer/assets/15572698/2f0cb7a8-2ae7-4202-a726-0f010439a6ae)
