### ISSUE TITLE
JSON Schema for multiple function choices

### ISSUE THREAD

**Issue by jamestwhedbee** [noamgat/lm-format-enforcer#95]
Created from https://github.com/vllm-project/vllm/issues/4459

[Here is a minimal JSON schema to illustrate](https://github.com/noamgat/lm-format-enforcer/files/15164693/multi_function_schema.json)

## Valid examples
[valid_function_1.json](https://github.com/noamgat/lm-format-enforcer/files/15164789/valid_function_1.json)
[valid_function_2.json](https://github.com/noamgat/lm-format-enforcer/files/15164790/valid_function_2.json)
[valid_function_3.json](https://github.com/noamgat/lm-format-enforcer/files/15164791/valid_function_3.json)

## Invalid examples
[invalid_args.json](https://github.com/noamgat/lm-format-enforcer/files/15164795/invalid_args.json)
[invalid_args_2.json](https://github.com/noamgat/lm-format-enforcer/files/15164877/invalid_args_2.json)
[invalid_fields.json](https://github.com/noamgat/lm-format-enforcer/files/15164796/invalid_fields.json)
[invalid_name.json](https://github.com/noamgat/lm-format-enforcer/files/15164797/invalid_name.json)

**Comment by jamestwhedbee** [comment]
@noamgat let me know if there is anything else I can provide!

**Comment by jamestwhedbee** [comment]
@noamgat let me know if you want me to create a separate issue for this, but I am also noticing that a JSON schema like this

```json
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "arguments": {
        "type": "object"
      },
      "name": {
        "type": "string"
      }
    },
    "required": [
      "name",
      "arguments"
    ]
  },
  "minItems": 1
}
```

always returns almost correct JSON with the closing `]` omitted

```json
[
  {
    "name": "sums",
    "arguments": {
      "a": 5,
      "b": 6
    }
  },
  {
    "name": "sums",
    "arguments": {
      "a": 2,
      "b": 7
    }
  },
  {
    "name": "subtraction",
    "arguments": {
      "c": 3,
      "d": 3
    }
  }
```

**Comment by noamgat** [comment]
These are likely related, lets leave them in the same issue. I hope to get to it in the coming days.

**Comment by noamgat** [comment]
I've tried to solve the issue here:
https://github.com/noamgat/lm-format-enforcer/tree/feature/multi-function-schema
Can you give it a try?
`pip install git+https://github.com/noamgat/lm-format-enforcer.git@feature/multi-function-schema`
This does not yet solve top level object being array, will get to it soon.

**Comment by noamgat** [comment]
version 0.9.10 was released with this fix, so you can try it as well.

**Comment by jamestwhedbee** [comment]
Nice I will test this out later today

**Comment by jamestwhedbee** [comment]
@noamgat https://github.com/noamgat/lm-format-enforcer/pull/96 looks to have resolved the oneOf and the array bugs!
