### ISSUE TITLE
Purely Recursive JSON Schema Broken

### ISSUE THREAD

**Issue by NJordan72** [noamgat/lm-format-enforcer#98]
When working with a JSON Schema (generated from Pydantic v2) I get an error when creating a parser.

```python
from typing import List
from pydantic import BaseModel

from lmformatenforcer import JsonSchemaParser

class TreeNode(BaseModel):
    name: str
    children: List["TreeNode"]
    
parser = JsonSchemaParser(TreeNode.model_json_schema())
```

results in `raise Exception("Unsupported type " + str(value_schema.type)) Exception: Unsupported type None`

If I wrap the `TreeNode` in a simple response object everything works fine:

```python
from typing import List
from pydantic import BaseModel

from lmformatenforcer import JsonSchemaParser

class TreeNode(BaseModel):
    name: str
    children: List["TreeNode"]
    
class Result(BaseModel):
    tree: TreeNode
    
parser = JsonSchemaParser(Result.model_json_schema())
```

**Comment by noamgat** [comment]
Interesting, I will have a look in the next bug squash (unless you want to
dive in and submit a PR :) )
